// SVG bodies for the policy in shared/svg-safety.mjs (TAB-82, TAB-204): plain drawing it keeps, and hostile bodies the
// server refuses and the app's sanitizer must leave nothing harmful of.
import { MAX_SVG_BODY } from '../shared/svg-safety.mjs';

export const CLEAN_SVG = [
  '<path d="M1 2h3v4z"/>',
  '<path fill="#FFCC4D" d="M0 0"/><circle cx="1" cy="2" r="3" fill="currentColor"/>',
  '<defs><linearGradient id="a" x1="0" x2="1"><stop offset="0" stop-color="#fff"/><stop offset="1" stop-color="#000"/></linearGradient></defs><path fill="url(#a)" d="M0 0"/>',
  '<g fill="none" stroke="currentColor" stroke-width="2"><path d="M4 12h16"/></g>',
  '<clipPath id="c"><rect width="10" height="10"/></clipPath><g clip-path="url(&quot;#c&quot;)"><use href="#p"/><use xlink:href="#p" xmlns:xlink="http://www.w3.org/1999/xlink"/></g>',
  '<image href="data:image/png;base64,iVBORw0KGgo=" width="4" height="4"/>',
  '<filter id="f"><feGaussianBlur stdDeviation="2"/></filter><g filter="url(#f)"><path d="M0 0"/></g>',
  '<text x="1" y="2">a &amp; b</text>',
  '<path style="fill:#fff;stroke:url(#a)" d="M0 0"/>',
  '',
];

export const HOSTILE_SVG: [string, string][] = [
  ['a script', '<script>alert(1)</script>'],
  ['a script with odd case', '<ScRiPt>alert(1)</sCrIpT>'],
  ['a script in a nested tag', '<scr<script>ipt>alert(1)</script>'],
  ['a foreignObject', '<foreignObject><div>hi</div></foreignObject>'],
  ['an onload handler', '<path d="M0 0" onload="alert(1)"/>'],
  ['an uppercase handler with spaces', '<path d="M0 0" ONCLICK = "alert(1)"/>'],
  ['a handler in single quotes', "<g onmouseover='x()'><path d='M0 0'/></g>"],
  ['a javascript href', '<use href="javascript:alert(1)"/>'],
  ['a javascript xlink:href', '<use xlink:href="javascript:alert(1)"/>'],
  ['a javascript href with a tab inside', '<use href="java&#9;script:alert(1)"/>'],
  ['a javascript href with a named entity', '<use href="javascript&colon;alert(1)"/>'],
  ['a javascript href with a hex entity', '<use href="&#x6A;avascript:alert(1)"/>'],
  ['a javascript href with spaces first', '<use href="   javascript:alert(1)"/>'],
  ['a data: html href', '<use href="data:text/html;base64,PHNjcmlwdD4="/>'],
  ['a data: svg image', '<image href="data:image/svg+xml;base64,PHN2Zy8+" width="1" height="1"/>'],
  ['a data: svg use', '<use href="data:image/svg+xml,%3Csvg/%3E#a"/>'],
  ['a data: png in a use', '<use href="data:image/png;base64,AAAA"/>'],
  ['an http image', '<image href="https://evil.example/pixel.png" width="1" height="1"/>'],
  ['a protocol-relative image', '<image href="//evil.example/pixel.png" width="1" height="1"/>'],
  ['an external use', '<use href="https://evil.example/x.svg#a"/>'],
  ['an external xlink use', '<use xlink:href="http://evil.example/x.svg#a"/>'],
  ['a relative use', '<use href="other.svg#a"/>'],
  ['an src attribute', '<image src="https://evil.example/x.png"/>'],
  ['an iframe', '<iframe src="https://evil.example"></iframe>'],
  ['an embed', '<embed src="x"/>'],
  ['an object', '<object data="x"></object>'],
  ['a style element', '<style>@import url(https://evil.example/x.css);</style>'],
  ['an anchor', '<a href="https://evil.example"><path d="M0 0"/></a>'],
  ['an animation that sets a link', '<a><set attributeName="href" to="javascript:alert(1)"/></a>'],
  ['a set element', '<set attributeName="fill" to="red"/>'],
  ['an animate element', '<animate attributeName="x" from="0" to="1"/>'],
  ['an html element', '<div>hi</div>'],
  ['a namespaced script', '<svg:script>alert(1)</svg:script>'],
  ['an external url() in a paint', '<path fill="url(https://evil.example/x.svg#a)" d="M0 0"/>'],
  ['an external url() in a style', '<path style="fill:url(//evil.example/x)" d="M0 0"/>'],
  ['a url() hidden by a css escape', '<path style="fill:\\75rl(//evil.example/x)" d="M0 0"/>'],
  ['a style import', '<path style="@import url(#a)" d="M0 0"/>'],
  ['an image-set in a mask', `<g mask='image-set("//evil.example/t.png" 1x)'><path d="M0 0"/></g>`],
  ['an image() in a cursor', '<path style="cursor:image(//evil.example/t.png)" d="M0 0"/>'],
  ['a cross-fade in a mask', '<g mask="cross-fade(//evil.example/a.png, //evil.example/b.png)"><path d="M0 0"/></g>'],
  ['a url with a data address', '<path fill="url(data:image/svg+xml,x)" d="M0 0"/>'],
  ['a comment', '<path d="M0 0"/><!-- <script> -->'],
  ['a CDATA section', '<![CDATA[<script>alert(1)</script>]]>'],
  ['a doctype with an entity', '<!DOCTYPE svg [<!ENTITY x "y">]><path d="M0 0"/>'],
  ['a processing instruction', '<?xml version="1.0"?><path d="M0 0"/>'],
  ['a numeric character reference', '<text>&#60;script&#62;</text>'],
  ['an html entity', '<text>&nbsp;&lt</text>'],
  ['a base override', '<g xml:base="https://evil.example/"><use href="x"/></g>'],
  ['another namespace', '<g xmlns="http://www.w3.org/1999/xhtml"><path d="M0 0"/></g>'],
  ['an unquoted attribute', '<path d=M0 fill=red />'],
  ['a repeated attribute', '<path d="M0 0" d="M1 1"/>'],
  ['a tag that is never closed', '<g><path d="M0 0"/>'],
  ['tags that do not match', '<g><path d="M0 0"/></path></g>'],
  ['a stray bracket', '<path d="M0 0"/>>'],
  ['a stray tag start', '<path d="M0 0"/><'],
  ['a null byte', '<path d="M0 0"/>\u0000'],
  ['a line separator', '<text>a b</text>'],
  ['an attribute that breaks out', '<path d="M0 0" fill="red"><script>x</script>"/>'],
  // a browser skips only ASCII whitespace before a value: after any other space the value is unquoted and the handler is real
  ['a handler hidden by a no-break space', '<path title=\u00a0"x onclick=alert(1) y" d="M0 0"/>'],
  ['a handler hidden by an em space', '<path title=\u2003"x onclick=alert(1) y" d="M0 0"/>'],
  ['a handler hidden by a byte order mark', '<path title=\ufeff"x onclick=alert(1) y" d="M0 0"/>'],
  ['a handler hidden by an ideographic space', '<path title=\u3000"x onclick=alert(1) y" d="M0 0"/>'],
  ['an animation handler hidden by a no-break space', '<animate attributeName="x" dur="1s" to=\u00a0"1 onbegin=alert(1) y"/>'],
  ['a longer-than-allowed body', `<path d="${'M0 0'.repeat(MAX_SVG_BODY)}"/>`],
];
